#pragma once
#include <windows.h>

typedef void*          HINTERNET;
typedef unsigned short INTERNET_PORT;

typedef enum _WINHTTP_WEB_SOCKET_BUFFER_TYPE {
    WINHTTP_WEB_SOCKET_BINARY_MESSAGE_BUFFER_TYPE  = 0,
    WINHTTP_WEB_SOCKET_BINARY_FRAGMENT_BUFFER_TYPE = 1,
    WINHTTP_WEB_SOCKET_UTF8_MESSAGE_BUFFER_TYPE    = 2,
    WINHTTP_WEB_SOCKET_UTF8_FRAGMENT_BUFFER_TYPE   = 3,
    WINHTTP_WEB_SOCKET_CLOSE_BUFFER_TYPE           = 4
} WINHTTP_WEB_SOCKET_BUFFER_TYPE;

typedef enum _WINHTTP_WEB_SOCKET_CLOSE_STATUS {
    WINHTTP_WEB_SOCKET_SUCCESS_CLOSE_STATUS = 1000
} WINHTTP_WEB_SOCKET_CLOSE_STATUS;

#define WINHTTP_ACCESS_TYPE_NO_PROXY 1
#define WINHTTP_NO_PROXY_NAME        ((LPCWSTR)0)
#define WINHTTP_NO_PROXY_BYPASS      ((LPCWSTR)0)
#define WINHTTP_NO_REFERER           ((LPCWSTR)0)
#define WINHTTP_DEFAULT_ACCEPT_TYPES ((LPCWSTR*)0)
#define WINHTTP_NO_ADDITIONAL_HEADERS ((LPCWSTR)0)
#define WINHTTP_NO_REQUEST_DATA      ((LPVOID)0)
#define WINHTTP_HEADER_NAME_BY_INDEX ((LPCWSTR)0)
#define WINHTTP_NO_HEADER_INDEX      ((LPDWORD)0)
#define WINHTTP_OPTION_UPGRADE_TO_WEB_SOCKET 114
#define WINHTTP_QUERY_STATUS_CODE 19
#define WINHTTP_QUERY_FLAG_NUMBER 0x20000000

HINTERNET WinHttpOpen(LPCWSTR, DWORD, LPCWSTR, LPCWSTR, DWORD);
BOOL      WinHttpSetTimeouts(HINTERNET, int, int, int, int);
HINTERNET WinHttpConnect(HINTERNET, LPCWSTR, INTERNET_PORT, DWORD);
HINTERNET WinHttpOpenRequest(HINTERNET, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR*, DWORD);
BOOL      WinHttpSetOption(HINTERNET, DWORD, LPVOID, DWORD);
BOOL      WinHttpSendRequest(HINTERNET, LPCWSTR, DWORD, LPVOID, DWORD, DWORD, DWORD_PTR);
BOOL      WinHttpReceiveResponse(HINTERNET, LPVOID);
BOOL      WinHttpQueryHeaders(HINTERNET, DWORD, LPCWSTR, LPVOID, LPDWORD, LPDWORD);
BOOL      WinHttpReadData(HINTERNET, LPVOID, DWORD, LPDWORD);
BOOL      WinHttpCloseHandle(HINTERNET);
HINTERNET WinHttpWebSocketCompleteUpgrade(HINTERNET, DWORD_PTR);
DWORD     WinHttpWebSocketSend(HINTERNET, WINHTTP_WEB_SOCKET_BUFFER_TYPE, PVOID, DWORD);
DWORD     WinHttpWebSocketReceive(HINTERNET, PVOID, DWORD, DWORD*, WINHTTP_WEB_SOCKET_BUFFER_TYPE*);
DWORD     WinHttpWebSocketClose(HINTERNET, USHORT, PVOID, DWORD);
