#!/usr/bin/env python3
"""Regenerates src/hud/font.cpp from the font in font/.

The plugin fetches nothing, ever, so the fallback face is compiled into it as base64. This turns
the font file in the repository into that source file. Run it after replacing the font; it needs
nothing but a Python interpreter.

    tools/embed_font.py [path/to/font.ttf]
"""
import base64
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT = os.path.join(ROOT, "font", "Oswald-VariableFont_wght.ttf")
OUT = os.path.join(ROOT, "src", "hud", "font.cpp")

# A single string literal is capped at 65,535 bytes by MSVC, and a whole font's base64 lands
# close enough to that to be worth not finding out the hard way. It goes in as pieces.
CHUNK = 8192
PER_LINE = 96

MIME = {".ttf": "font/ttf", ".otf": "font/otf",
        ".woff": "font/woff", ".woff2": "font/woff2"}
FORMAT = {".ttf": "truetype", ".otf": "opentype",
          ".woff": "woff", ".woff2": "woff2"}


def weight_range(raw: bytes) -> str:
    """The wght axis of a variable font, as a CSS font-weight range.

    A @font-face has to declare the range for the browser to instance the font at a weight
    rather than synthesise one, so it is read out of fvar here instead of being written down
    twice. A static font has no fvar and gets the single weight it is.
    """
    import struct
    try:
        count = struct.unpack(">H", raw[4:6])[0]
        tables = {}
        for i in range(count):
            off = 12 + 16 * i
            tables[raw[off:off + 4]] = struct.unpack(">I", raw[off + 8:off + 12])[0]
        if b"fvar" not in tables:
            return ""
        o = tables[b"fvar"]
        axes_off, axis_count, axis_size = (struct.unpack(">H", raw[o + 4:o + 6])[0],
                                           struct.unpack(">H", raw[o + 8:o + 10])[0],
                                           struct.unpack(">H", raw[o + 10:o + 12])[0])
        for a in range(axis_count):
            ao = o + axes_off + a * axis_size
            if raw[ao:ao + 4] != b"wght":
                continue
            lo = struct.unpack(">i", raw[ao + 4:ao + 8])[0] / 65536.0
            hi = struct.unpack(">i", raw[ao + 12:ao + 16])[0] / 65536.0
            return f"{lo:g} {hi:g}"
    except Exception:
        pass
    return ""


def main() -> int:
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    ext = os.path.splitext(path)[1].lower()
    if ext not in MIME:
        print(f"{path}: not a font this can embed ({', '.join(sorted(MIME))})", file=sys.stderr)
        return 1

    with open(path, "rb") as fh:
        raw = fh.read()
    b64 = base64.b64encode(raw).decode("ascii")

    weights = weight_range(raw) or "400"
    parts = [b64[i:i + CHUNK] for i in range(0, len(b64), CHUNK)]
    body = []
    for part in parts:
        lines = [part[i:i + PER_LINE] for i in range(0, len(part), PER_LINE)]
        body.append("\n".join(f'    "{line}"' for line in lines) + ",")
    body.append("    nullptr,")

    with open(OUT, "w", encoding="utf8", newline="\n") as fh:
        fh.write(TEMPLATE % {
            "name": os.path.basename(path),
            "mime": MIME[ext],
            "format": FORMAT[ext],
            "weights": weights,
            "bytes": len(raw),
            "chars": len(b64),
            "parts": len(parts),
            "body": "\n".join(body),
        })
    print(f"{OUT}: {os.path.basename(path)}, {len(raw)} bytes -> "
          f"{len(b64)} characters of base64 in {len(parts)} pieces, weights {weights}")
    return 0


TEMPLATE = '''#include "hud/font.h"

// %(name)s, base64. Generated by tools/embed_font.py from the file in font/; do not edit.
//
// The old HUD was drawn in the game's font 4, Chalet Comprime Cologne Sixty. That face is
// licensed and is not this project's to redistribute, so it cannot be shipped here. It is still
// asked for first by name, so a client that has it installed uses it, and a copy placed next to
// the .asi is loaded ahead of everything else (see the font_file setting).
//
// This is what gets used when neither is available. Whatever it is, the script measures it at
// run time and squeezes it horizontally to the widths taken off the old HUD screenshots, so the
// layer keeps the original's proportions rather than rendering the same text wider at the same
// height.
//
// It is compiled in rather than fetched because the plugin makes no outbound connection of any
// kind: the one socket it opens is to loopback. The licence is in font/OFL.txt.
//
// %(bytes)d bytes, %(chars)d characters of base64.
namespace hud {

const char* const kFallbackFontMime    = "%(mime)s";
const char* const kFallbackFontFormat  = "%(format)s";

// The weights the face can actually be drawn at, for the @font-face to declare. A range means
// the browser instances the variable font instead of faking a heavier one.
const char* const kFallbackFontWeights = "%(weights)s";

// A single string literal is capped at 65,535 bytes by MSVC, which a whole font's base64 sits
// close enough to that it is not worth relying on. Null terminated.
const char* const kFallbackFontBase64Parts[] = {
%(body)s
};

}  // namespace hud
'''

if __name__ == "__main__":
    raise SystemExit(main())
